### ISSUE TITLE
Error on line 349 

### ISSUE THREAD

**Issue by magicianjarden** [MadCatMining/codeswholesale-woocommerce#2]
I keep getting the following error when activating

( ! )  Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No  connection could be made because the target machine actively refused it.  in C:\Users\user\Local  Sites\sitename\app\public\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php  on line 349

**Comment by MadCatMining** [comment]
Do yo have all of the requirements fulfilled? 
Is PDO sqlite php module installed and enabled?
Plugin is not able to communicate with database.

**Comment by magicianjarden** [comment]
I switched to Laragon for easier testing and editing...

Fatal error: Uncaught PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php:349 Stack trace: #0 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(349): PDO->__construct('mysql:host=;dbn...', '', '') #1 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(120): CodesWholesale->configure_cw_client() #2 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(294): CodesWholesale->__construct() #3 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(459): CodesWholesale::instance() #4 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(462): CW() #5 C:\laragon\www\gamingsite\wp-admin\includes\plugin.php(2314): include_once('C:\\laragon\\www\\...') #6 C:\laragon\www\gamingsite\wp in C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php on line 349

I am using: 
SQLite database driver drop-in.
Version 2.1.1 | By WordPress Performance Team to migrate the server to SQL LITE

is there an easier way to do this?

**Comment by MadCatMining** [comment]
Php extension in php.ini is uncommented?
extension=pdo_mysql

**Comment by MadCatMining** [comment]
Php extension in php.ini is uncommented?
extension=pdo_mysql

**Comment by magicianjarden** [comment]
Correct.

**Comment by MadCatMining** [comment]
PDO Authentication Error Solution


User
in this like of code:

'db' => new PDO('mysql:host=' . $wpdb->dbhost . ';dbname=' . $wpdb->dbname, $wpdb->dbuser, $wpdb->dbpassword),

i get the error:

Fatal error: Uncaught PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php:349 Stack trace: #0 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(349): PDO->__construct('mysql:host=;dbn...', '', '') #1 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(120): CodesWholesale->configure_cw_client() #2 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(294): CodesWholesale->__construct() #3 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(459): CodesWholesale::instance() #4 C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php(462): CW() #5 C:\laragon\www\gamingsite\wp-admin\includes\plugin.php(2314): include_once('C:\laragon\www\...') #6 C:\laragon\www\gamingsite\wp in C:\laragon\www\gamingsite\wp-content\plugins\codeswholesale-woocommerce\codeswholesale.php on line 349

any idea what can be the reson?

ChatGPT
The error message you're encountering suggests that the MySQL server is requesting an authentication method that is not recognized by the client. This issue is commonly caused by compatibility problems between the MySQL server and the version of PHP's PDO extension you're using.

The error specifically mentions the authentication method "caching_sha2_password," which was introduced in MySQL version 8.0.4. If you're using an older version of the PDO extension that does not support this authentication method, you will encounter this error.

To resolve this issue, you have a few options:

Update PDO Extension: Update your PHP installation or the PDO extension to a version that supports the "caching_sha2_password" authentication method. Ensure that you're using a version of PHP and PDO that is compatible with the MySQL server you're connecting to.

Change Authentication Method: If updating the PDO extension is not feasible, you can try changing the authentication method used by the MySQL server. You can do this by modifying the MySQL server's configuration file (typically my.cnf or my.ini) and setting the default_authentication_plugin option to a compatible authentication method such as mysql_native_password. After making this change, restart the MySQL server.

**Comment by MadCatMining** [comment]
The error message you're encountering suggests that the MySQL server is requesting an authentication method that is not recognized by the client. This issue is commonly caused by compatibility problems between the MySQL server and the version of PHP's PDO extension you're using.

The error specifically mentions the authentication method "caching_sha2_password," which was introduced in MySQL version 8.0.4. If you're using an older version of the PDO extension that does not support this authentication method, you will encounter this error.

To resolve this issue, you have a few options:

Update PDO Extension: Update your PHP installation or the PDO extension to a version that supports the "caching_sha2_password" authentication method. Ensure that you're using a version of PHP and PDO that is compatible with the MySQL server you're connecting to.

Change Authentication Method: If updating the PDO extension is not feasible, you can try changing the authentication method used by the MySQL server. You can do this by modifying the MySQL server's configuration file (typically my.cnf or my.ini) and setting the default_authentication_plugin option to a compatible authentication method such as mysql_native_password. After making this change, restart the MySQL server.

**Comment by MadCatMining** [comment]
I'm not a creator of this plugin. I don't know your specific environments. From what i can tell - plugin was coded under Mac, works on Linux. Don't think windows based servers were tested.
